### ISSUE TITLE
Shouldn't have companies with no published contracts (1)

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#12]
Don't list companies with no associated contracts.

**Comment by jerico** [comment]
https://github.com/jerico/ph-eiti-contracts-portal/issues/31

With the request of PH-EITI to use contract name as company name, this has been addressed as well

**Comment by jerico** [comment]
This is fixed

**Comment by charlesyoung** [comment]
Still dont find contracts for LNL Archipelago Minerals, Incorporated (Operator)

**Comment by jerico** [comment]
An issue with the API was filed: https://github.com/younginnovations/resourcecontracts-api/issues/6

Will update this issue as I get a response
