### ISSUE TITLE
Open Twitter and Facebook links in separate windows (2)

### ISSUE THREAD

**Issue by charlesyoung** [jerico/ph-eiti-contracts-portal#14]

**Comment by jerico** [comment]
This is fixed

**Comment by charlesyoung** [comment]
This is still not working on the http://contracts.ph-eiti.org/contact page.

**Comment by jerico** [comment]
This is fixed
